### ISSUE TITLE
IDEA 搭建开发环境，无法启动，Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Samurais** [chatopera/cskefu#388]
```
InputStream input = SystemEnvHelper.class.getClassLoader().getResourceAsStream(
                    "application.properties")
```
返回了 null 值。造成

```

java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.chatopera.cc.util.SystemEnvHelper.getProps(SystemEnvHelper.java:97)
	at com.chatopera.cc.util.SystemEnvHelper.parseFromApplicationProps(SystemEnvHelper.java:81)
	at com.chatopera.cc.Application.<clinit>(Application.java:68)

```

**Comment by Samurais** [comment]
临时解决方案：


```
SPRING_PROFILES_ACTIVE=dev mvn spring-boot:run
```
