### ISSUE TITLE
elasticsearch某种情况下会触发大规模写日志写满磁盘

### ISSUE THREAD

**Issue by fastuser999** [chatopera/cskefu#389]
## 来自

- 公司：
- 产品：

# 描述
docker overlay2下面的日志样例：
java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/cskefu/_state/state-21.st.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at org.elasticsearch.gateway.MetaDataStateFormat.write(MetaDataStateFormat.java:112)
        at org.elasticsearch.gateway.MetaStateService.writeIndex(MetaStateService.java:135)
        at org.elasticsearch.gateway.GatewayMetaState.clusterChanged(GatewayMetaState.java:160)
        at org.elasticsearch.gateway.Gateway.clusterChanged(Gateway.java:185)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:622)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2021-01-05 04:34:54,779][WARN ][index.engine             ] [Diablo] [cskefu][4] failed engine [index]
java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/cskefu/4/index/_2.fdx
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:271)
        at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:224)
        at org.apache.lucene.store.FileSwitchDirectory.createOutput(FileSwitchDirectory.java:155)
        at org.apache.lucene.store.RateLimitedFSDirectory.createOutput(RateLimitedFSDirectory.java:40)
        at org.apache.lucene.store.FilterDirectory.createOutput(FilterDirectory.java:73)
        at org.apache.lucene.store.LockValidatingDirectoryWrapper.createOutput(LockValidatingDirectoryWrapper.java:44)
        at org.apache.lucene.store.TrackingDirectoryWrapper.createOutput(TrackingDirectoryWrapper.java:43)
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.<init>

docker container貌似会把异常堆栈一行一条的写到json.log，导致磁盘很快就满了。

## 预期行为

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
该情况是 ES Flush 缓存到磁盘导致，

1）查看 ES 中数据内容中，什么项目占的多，使用 es head 查看, 春松客服 docker compose 部署得到的 es 已经安装了 es head 插件，通过 http://YOUR_ES_IP:PORT/_plugin/head/ 查看，参考 https://github.com/mobz/elasticsearch-head 。

2）取保磁盘资源比较大

3）设置 ES 的相关字段来优化磁盘写入情况，参考 es 2.4.x 的配置文件，更改 https://github.com/chatopera/cskefu/blob/osc/database/elasticsearch/config/elasticsearch.yml

如有 root cause 发现，请更新到本 Issue, 感谢您的反馈！

**Comment by Samurais** [comment]
java.nio.file.AccessDeniedException 是没有权限写文件，确定是写满磁盘导致这个Exception?

**Comment by Samurais** [comment]
确认docker容器运行的用户具有写入 databases/elasticsearch/data/nodes 的权限。

**Comment by Samurais** [comment]
无法重现，暂时关闭。
