### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by reynold-Yang** [chatopera/cskefu#411]
环境搭建好后，运行报错
系统为 mac os
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.chatopera.cc.util.SystemEnvHelper.getProps(SystemEnvHelper.java:95)
	at com.chatopera.cc.util.SystemEnvHelper.parseFromApplicationProps(SystemEnvHelper.java:79)
	at com.chatopera.cc.Application.<clinit>(Application.java:68)

**Comment by hailiang-wang** [comment]
- 是否按照文档搭建？请添加 IDEA SpringBoot 应用配置的截图
https://docs.chatopera.com/products/cskefu/osc/engineering.html

- 是否使用 application-dev.properties 配置?
application-dev.properties

**Comment by reynold-Yang** [comment]
老师您好，
我是按照文档搭建的
没有使用 applocation-dev.properties  ，都是使用的项目默认的配置
下面是我的 IDEA SpringBoot 截图，请您帮忙看看
![image](https://user-images.githubusercontent.com/33046081/109378090-a7654d80-790a-11eb-8f92-349b94a32e62.png)

**Comment by hailiang-wang** [comment]
Main Class 没有找到，点击右侧 [...] 手动查找。
文件位置
https://github.com/chatopera/cskefu/blob/osc/contact-center/app/src/main/java/com/chatopera/cc/Application.java

鉴于您对 Java 基础和开发环境不了解，建议购买春松客服大讲堂，一些初级问题，不在 Issue 处理范围内。
https://ke.qq.com/course/464050

感谢！
