### ISSUE TITLE
docker-compose up -d elasticsearch 报错

### ISSUE THREAD

**Issue by reynold-Yang** [chatopera/cskefu#412]
## 来自

- 公司：
- 产品：

# 描述

## 功能
docker-com

# 环境

## 操作系统

- [1 ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本
e04ace620f99a32186cf6b524f4bf252cb377740
Git commit hash (`git rev-parse HEAD`)

报错内容
[2021-02-26 17:42:15,401][WARN ][watcher ] cannot notify file changes listener

java.lang.IllegalArgumentException: script file extension not supported [gitignore]

at org.elasticsearch.script.ScriptService.getScriptEngineServiceForFileExt(ScriptService.java:220)

at org.elasticsearch.script.ScriptService.access$1300(ScriptService.java:82)

at org.elasticsearch.script.ScriptService$ScriptChangesListener.onFileInit(ScriptService.java:531)

at org.elasticsearch.watcher.FileWatcher$FileObserver.onFileCreated(FileWatcher.java:256)

at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:166)

at org.elasticsearch.watcher.FileWatcher$FileObserver.createChild(FileWatcher.java:173)

at org.elasticsearch.watcher.FileWatcher$FileObserver.listChildren(FileWatcher.java:188)

at org.elasticsearch.watcher.FileWatcher$FileObserver.onDirectoryCreated(FileWatcher.java:299)

at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:162)

at org.elasticsearch.watcher.FileWatcher$FileObserver.access$000(FileWatcher.java:75)

at org.elasticsearch.watcher.FileWatcher.doInit(FileWatcher.java:65)

at org.elasticsearch.watcher.AbstractResourceWatcher.init(AbstractResourceWatcher.java:36)

at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:133)

at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:126)

at org.elasticsearch.script.ScriptService.<init>(ScriptService.java:191)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)

at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)

at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)

at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)

at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)

at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)

at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)

at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)

at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)

at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)

at org.elasticsearch.common.inject.SingleMethodInjector.inject(SingleMethodInjector.java:70)

at org.elasticsearch.common.inject.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:96)

at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:95)

at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)

at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)

at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)

at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)

at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)

at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)

at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)

at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)

at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:879)

at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)

at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)

at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)

at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)

at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)

at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)

at org.elasticsearch.node.Node.<init>(Node.java:213)

at org.elasticsearch.node.Node.<init>(Node.java:140)

at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)

at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)

at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)

at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)

**Comment by hailiang-wang** [comment]
该提示为 WARN，不影响使用。
