### ISSUE TITLE
HTTPS报错

### ISSUE THREAD

**Issue by xihongjian** [chatopera/cskefu#422]
## 描述
[onMessage] error ^[[32m[DefaultMessageListenerContainer-1]^[[0;39m
com.chatopera.bot.exception.ChatbotException: kong.unirest.UnirestException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.chatopera.bot.sdk.Chatbot.command(Chatbot.java:208)
        at com.chatopera.bot.sdk.Chatbot.conversation(Chatbot.java:369)
        at com.chatopera.cc.plugins.chatbot.ChatbotEventSubscription.chat(ChatbotEventSubscription.java:108)
        at com.chatopera.cc.plugins.chatbot.ChatbotEventSubscription.onMessage(ChatbotEventSubscription.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:180)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:112)
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:104)
        at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:69)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:719)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:679)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:649)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:255)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1168)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1160)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1057)
        at java.lang.Thread.run(Thread.java:745)

使用nginx代理 通过https 访问。   报如上错误。

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
参考同问题的讨论，

https://github.com/chatopera/cskefu/issues?q=ValidatorException%3A+PKIX+path+building+failed
