### ISSUE TITLE
访客无法发送消息：Blocked a frame with origin "xxx" from accessing a cross-origin frame

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/cskefu#475]
## 问题

打开 [https://www.cskefu.com/](https://www.cskefu.com/) “在线客服”，发送文本。

![image](https://user-images.githubusercontent.com/3538629/134274955-a0a0b875-63ba-451a-94e5-3f9fffb19b9b.png)

console log 日志

![image](https://user-images.githubusercontent.com/3538629/134274780-5ad33095-2e40-409c-a27c-3983e8502a9b.png)

Chrome 浏览器发现如下错误：

```
Uncaught DOMException: Blocked a frame with origin "https://oh-my.cskefu.com" from accessing a cross-origin frame.
    at contents (https://oh-my.cskefu.com/js/jquery-1.10.2.min.js:5:23139)
    at Function.map (https://oh-my.cskefu.com/js/jquery-1.10.2.min.js:4:6171)
    at init.x.fn.<computed> [as contents] (https://oh-my.cskefu.com/js/jquery-1.10.2.min.js:5:23219)
    at KEditor.afterCreate (https://oh-my.cskefu.com/im/index.html?appid=0nhckh&orgi=cskefu&client=d9452e5719aa484898791e6f6f64480e&aiid=7c798a3a5b7e4be48a44d1193c24e90d&userid=2eb8dcac14b4d6452978d093d7a4361b&sessionid=9f9f87475627428886e0b9cae897d156&skill=2c9280867b341e68017bb41e93c70515&title=%E6%98%A5%E6%9D%BE%E5%AE%A2%E6%9C%8D%20%7C%20%E6%99%BA%E8%83%BD%E5%AE%A2%E6%9C%8D%E7%B3%BB%E7%BB%9F_%E5%BC%80%E6%BA%90%E6%99%BA%E8%83%BD%E5%AE%A2%E6%9C%8D_%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%AE%A2%E6%9C%8D&traceid=15623fb1b07949338a536750a4aac1dc&url=https%3A%2F%2Fwww.cskefu.com%2F&t=1632278225986:75:52)
    at KEdit.afterCreate (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:5047:31)
    at ready (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:3701:25)
    at KEdit.init (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:3717:24)
    at new KEdit (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:3610:7)
    at _edit (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:3845:9)
    at KEditor.create (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:4978:26)
8index.html?appid=0nhckh&orgi=cskefu&client=d9452e5719aa484898791e6f6f64480e&aiid=7c798a3a5b7e4be48a44d1193c24e90d&userid=2eb8dcac14b4d6452978d093d7a4361b&sessionid=9f9f87475627428886e0b9cae897d156&skill=2c9280867b341e68017bb41e93c70515&title=春松客服 | 智能客服系统_开源智能客服_机器人客服&traceid=15623fb1b07949338a536750a4aac1dc&url=https%3A%2F%2Fwww.cskefu.com%2F&t=1632278225986:579 Uncaught TypeError: Cannot read properties of undefined (reading 'sync')
    at sendMessage (index.html?appid=0nhckh&orgi=cskefu&client=d9452e5719aa484898791e6f6f64480e&aiid=7c798a3a5b7e4be48a44d1193c24e90d&userid=2eb8dcac14b4d6452978d093d7a4361b&sessionid=9f9f87475627428886e0b9cae897d156&skill=2c9280867b341e68017bb41e93c70515&title=春松客服 | 智能客服系统_开源智能客服_机器人客服&traceid=15623fb1b07949338a536750a4aac1dc&url=https%3A%2F%2Fwww.cskefu.com%2F&t=1632278225986:579)
    at HTMLButtonElement.onclick (index.html?appid=0nhckh&orgi=cskefu&client=d9452e5719aa484898791e6f6f64480e&aiid=7c798a3a5b7e4be48a44d1193c24e90d&userid=2eb8dcac14b4d6452978d093d7a4361b&sessionid=9f9f87475627428886e0b9cae897d156&skill=2c9280867b341e68017bb41e93c70515&title=春松客服 | 智能客服系统_开源智能客服_机器人客服&traceid=15623fb1b07949338a536750a4aac1dc&url=https%3A%2F%2Fwww.cskefu.com%2F&t=1632278225986:463)
```

## 浏览器

* Firefox 浏览器没有这个问题

* Chrome 版本
版本 93.0.4577.82（正式版本） （64 位）

**Comment by hailiang-wang** [comment]
使用 Chrome 无痕模式，无法复现。

**Comment by mukaiu** [comment]
osschat

**Comment by mukaiu** [comment]
osschat

**Comment by mukaiu** [comment]
osschat

**Comment by mukaiu** [comment]
osschat

**Comment by mukaiu** [comment]
chat

**Comment by mukaiu** [comment]
chat

**Comment by mukaiu** [comment]
chat

**Comment by mukaiu** [comment]
chat

**Comment by mukaiu** [comment]
chat

**Comment by mukaiu** [comment]
chat

**Comment by mukaiu** [comment]
test

**Comment by mukaiu** [comment]
oss

**Comment by mukaiu** [comment]
osst
