### ISSUE TITLE
关于把app抽出来单独作为boot项目跑遇到的问题

### ISSUE THREAD

**Issue by yangshenwei** [chatopera/cskefu#514]
##背景
docker环境异常，在本地单独运行app子项目为boot项目
##问题
先在本地运行elasticsearch 2.2.0和activemq 5.16.3版本，启动服务后进入8035端口报500
##异常信息
2021-11-24 09:17:51.802 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/templates/] with root cause [http-nio-8035-exec-2] 
java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/templates/
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at de.neuland.pug4j.spring.template.SpringTemplateLoader.getResourceName(SpringTemplateLoader.java:58)
	at de.neuland.pug4j.spring.template.SpringTemplateLoader.getResource(SpringTemplateLoader.java:46)
	at de.neuland.pug4j.spring.template.SpringTemplateLoader.getReader(SpringTemplateLoader.java:36)
	at de.neuland.pug4j.PugConfiguration.templateExists(PugConfiguration.java:178)
	at de.neuland.pug4j.spring.view.PugView.checkResource(PugView.java:71)
	at org.springframework.web.servlet.view.UrlBasedViewResolver.loadView(UrlBasedViewResolver.java:510)
	at org.springframework.web.servlet.view.AbstractCachingViewResolver.createView(AbstractCachingViewResolver.java:244)
	at org.springframework.web.servlet.view.UrlBasedViewResolver.createView(UrlBasedViewResolver.java:473)
	at org.springframework.web.servlet.view.AbstractCachingViewResolver.resolveViewName(AbstractCachingViewResolver.java:156)
	at org.springframework.web.servlet.DispatcherServlet.resolveViewName(DispatcherServlet.java:1325)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1263)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:54)

**Comment by hailiang-wang** [comment]
集成开发环境是 IDEA？
Server 的配置帮忙做一下截图。

关联历史问题：https://github.com/chatopera/cskefu/issues/408

**Comment by hailiang-wang** [comment]
操作系统是 Windows ？

**Comment by yangshenwei** [comment]
集成开发环境是idea，JDK1.8
操作系统是Windows

**Comment by yangshenwei** [comment]
##server配置截图
![image](https://user-images.githubusercontent.com/59436868/143155897-0b319771-36e7-44fc-9d9d-fa5389a8579b.png)

**Comment by yangshenwei** [comment]
你好，刚刚进行了一下测试，在MAC上是没问题的，代码没发生任何改变。在window下报上面的异常信息，请问是需要对代码哪部分做兼容性的修改么

**Comment by hailiang-wang** [comment]
异常信息就是这个吗？

```
2021-11-24 09:17:51.802 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/templates/] with root cause [http-nio-8035-exec-2] 
java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/templates/
```

**Comment by yangshenwei** [comment]
是这个异常信息，windows系统在手动修改完PugConfig类后提示新异常信息。
##PugConfig类修改
![image](https://user-images.githubusercontent.com/59436868/143169394-def0ba1e-6a5d-4285-bfad-1e4c1c38ed74.png)
##新的异常信息
2021-11-24 11:21:23.694 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template "/login", template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause [http-nio-8035-exec-2] 
org.thymeleaf.exceptions.TemplateInputException: Error resolving template "/login", template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:246)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1104)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
	at org.thymeleaf.spring4.view.ThymeleafView.renderFragment(ThymeleafView.java:335)
	at org.thymeleaf.spring4.view.ThymeleafView.render(ThymeleafView.java:190)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:54)

**Comment by hailiang-wang** [comment]
请 fork 春松客服，
https://github.com/chatopera/cskefu

并将变更提交到你 fork 的仓库，需要看你的变更代码。
感谢！

**Comment by yangshenwei** [comment]
你好，我是按照关联的408修改的，还是报以上的异常：Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/templates/] with root cause [http-nio-8035-exec-2] 
java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/templates/
##自己修改说明
之前的工单已经说明jar包已升级，故将修改处改回原代码

**Comment by hailiang-wang** [comment]
您的这些描述，是很花时间的，但是上下文还不充分帮助解决问题！
强烈建议，FORK 项目，提交你的变更到你的 FORK 项目上，在此处添加 COMMIT 链接。这样有直接的代码比对。
