### ISSUE TITLE
环境搭建好了后，启动一直连不上activemq，浏览器能成功访问mq

### ISSUE THREAD

**Issue by happy-snail** [chatopera/cskefu#602]
`javax.jms.JMSException: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36)
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:374)
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:304)
	at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:244)
	at org.messaginghub.pooled.jms.JmsPoolConnectionFactory.createProviderConnection(JmsPoolConnectionFactory.java:650)
	at org.messaginghub.pooled.jms.JmsPoolConnectionFactory$1.makeObject(JmsPoolConnectionFactory.java:107)
	at org.messaginghub.pooled.jms.JmsPoolConnectionFactory$1.makeObject(JmsPoolConnectionFactory.java:104)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1041)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addObject(GenericKeyedObjectPool.java:1238)
	at org.messaginghub.pooled.jms.JmsPoolConnectionFactory.createJmsPoolConnection(JmsPoolConnectionFactory.java:704)
	at org.messaginghub.pooled.jms.JmsPoolConnectionFactory.createConnection(JmsPoolConnectionFactory.java:236)
	at org.messaginghub.pooled.jms.JmsPoolConnectionFactory.createConnection(JmsPoolConnectionFactory.java:231)
	at org.springframework.boot.actuate.jms.JmsHealthIndicator.doHealthCheck(JmsHealthIndicator.java:52)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:81)
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:38)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:108)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:119)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:105)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:83)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:70)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:75)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:77)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:121)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:96)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:525)
	at org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:488)
	at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
	at org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:169)
	at org.apache.activemq.transport.InactivityMonitor.start(InactivityMonitor.java:52)
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
	at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:64)
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:354)
	... 55 common frames omitted
2022-02-15 09:42:27.561 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.webim.agent' - retrying using FixedBackOff{interval=5000, currentAttempts=2, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:29.578 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.agent.audit' - retrying using FixedBackOff{interval=5000, currentAttempts=1, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:31.615 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.agent.session.retired' - retrying using FixedBackOff{interval=5000, currentAttempts=1, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:33.656 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.webim.onlineuser' - retrying using FixedBackOff{interval=5000, currentAttempts=2, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:35.670 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.socketio.agent.disconnect' - retrying using FixedBackOff{interval=5000, currentAttempts=2, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:37.748 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.agent.audit' - retrying using FixedBackOff{interval=5000, currentAttempts=2, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:39.761 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.webim.agent' - retrying using FixedBackOff{interval=5000, currentAttempts=3, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:41.771 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.im.onlineuser.blacklist' - retrying using FixedBackOff{interval=5000, currentAttempts=3, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:43.786 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.socketio.agent.disconnect' - retrying using FixedBackOff{interval=5000, currentAttempts=3, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:45.800 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.webim.onlineuser' - retrying using FixedBackOff{interval=5000, currentAttempts=3, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:47.811 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.agent.session.retired' - retrying using FixedBackOff{interval=5000, currentAttempts=2, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:49.824 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.im.onlineuser.blacklist' - retrying using FixedBackOff{interval=5000, currentAttempts=4, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:51.841 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.webim.agent' - retrying using FixedBackOff{interval=5000, currentAttempts=4, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:53.850 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.agent.audit' - retrying using FixedBackOff{interval=5000, currentAttempts=3, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:55.861 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.agent.session.retired' - retrying using FixedBackOff{interval=5000, currentAttempts=3, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:57.868 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.webim.onlineuser' - retrying using FixedBackOff{interval=5000, currentAttempts=4, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:42:59.879 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.socketio.agent.disconnect' - retrying using FixedBackOff{interval=5000, currentAttempts=4, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:43:01.892 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.agent.audit' - retrying using FixedBackOff{interval=5000, currentAttempts=4, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
2022-02-15 09:43:03.905 ERROR o.s.j.l.DefaultMessageListenerContainer - Could not refresh JMS Connection for destination 'cskefu.webim.agent' - retrying using FixedBackOff{interval=5000, currentAttempts=5, maxAttempts=unlimited}. Cause: Could not connect to broker URL: tcp://192.168.248.85:61616. Reason: java.net.ConnectException: Connection refused: connect [DefaultMessageListenerContainer-1] 
`

**Comment by happy-snail** [comment]
1
