### ISSUE TITLE
会话监控和历史会话内容为空 

### ISSUE THREAD

**Issue by vicviz** [chatopera/cskefu#616]
# 现在行为

会话监控和历史会话页面中，没有任何的内容，但其实是有现在进行的会话以及很多之前的已结束的会话的

# 预期行为

能正常看到会话监控和历史会话的内容

同时，后台出现了异常

```
| 2022-03-20 21:02:56.665 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find com.chatopera.cc.model.User with id 2c9380867f898b72017f917691304e5f; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.chatopera.cc.model.User with id 2c938086***] with root cause [http-nio-8035-exec-1]
contact-center_1 | javax.persistence.EntityNotFoundException: Unable to find com.chatopera.cc.model.User with id 2c9380867f898b72017f917691304e5f
contact-center_1 | at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:144)
contact-center_1 | at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:227)
contact-center_1 | at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:262)
contact-center_1 | at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:121)
contact-center_1 | at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:89)
contact-center_1 | at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1129)
contact-center_1 | at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1022)
contact-center_1 | at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:639)
contact-center_1 | at org.hibernate.type.EntityType.resolve(EntityType.java:431)
contact-center_1 | at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:154)
contact-center_1 | at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:128)
contact-center_1 | at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1133)

```

**Comment by vicviz** [comment]
开了三个浏览器，一个用户，一个客服，一个系统管理 员。
明明用户是和客服在聊着的，系统理员或者管理员或者高级客服，打开会话监控都是空的。

打出了下面的提示：
2022-03-20 23:02:53.376 [http-nio-8035-exec-1] INFO  c.c.cc.controller.apps.AgentAuditController - [index] skill null, agentno null, logined 4028cac36***
2022-03-20 23:02:53.382 [http-nio-8035-exec-1] INFO  c.c.cc.controller.apps.AgentAuditController - [index] agent users size: 0

**Comment by hailiang-wang** [comment]
请截图，展示一下高级客服的角色权限，配置了哪些，并且高级客服和客服，是不是在一个组织内，或者是上级组织内。

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by vicviz** [comment]
> 请截图，展示一下高级客服的角色权限，配置了哪些，并且高级客服和客服，是不是在一个组织内，或者是上级组织内。
> 
> **请使用以下工具提升沟通效率**
> 
> * 工单管理： https://github.com/chatopera/cskefu/issues
> * 文档中心：https://docs.chatopera.com/
> * 商务洽谈：https://www.chatopera.com/mail.html
> 
> **春松客服大讲堂**
> 
> https://chatopera.blog.csdn.net/article/details/121599407

![1](https://user-images.githubusercontent.com/2442699/159283741-a9553cf6-e2d1-4f71-a5cf-110fed802c6a.jpeg)
![2](https://user-images.githubusercontent.com/2442699/159283749-6d02f030-4afa-4a03-bb90-96ebc325c26a.jpeg)
![3](https://user-images.githubusercontent.com/2442699/159283757-2c257139-4460-4d3f-a9a3-d5bc2bc03490.jpeg)
![4](https://user-images.githubusercontent.com/2442699/159283763-0676066f-24f1-4baf-a605-747a77dfd0b7.jpeg)

**Comment by vicviz** [comment]
这里所有的人，都在这个默认的售前从席A组中，然后高级坐席有所有的角色权限。

今天测试，还发现了问题是：除了管理员，突然所有的客服，都不能安排坐席了，有用户来了，如果管理员和高级客服没有登录，那么也不会安排坐席

**Comment by vicviz** [comment]
同时还伴有这样的错：



2022-03-21 22:47:27.970 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: non null hash key required] with root cause [http-nio-8035-exec-27]
java.lang.IllegalArgumentException: non null hash key required
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.data.redis.core.AbstractOperations.rawHashKey(AbstractOperations.java:150)
	at org.springframework.data.redis.core.DefaultHashOperations.get(DefaultHashOperations.java:47)
	at com.chatopera.cc.cache.RedisCommand.getHashKV(RedisCommand.java:252)
	at com.chatopera.cc.cache.Cache.findOneSystemMapByIdAndOrgi(Cache.java:741)
	at com.chatopera.cc.cache.Cache$$FastClassBySpringCGLIB$$234e2808.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
	at com.chatopera.cc.cache.Cache$$EnhancerBySpringCGLIB$$36c27ea8.findOneSystemMapByIdAndOrgi(<generated>)
	at com.chatopera.cc.controller.apps.IMController.index(IMController.java:625)
	at sun.reflect.GeneratedMethodAccessor1105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:54)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.chatopera.cc.config.ApiRequestMatchingFilter.doFilter(ApiRequestMatchingFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.chatopera.cc.config.DelegateRequestMatchingFilter.doFilter(DelegateRequestMatchingFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:171)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.micrometer.spring.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2022-03-21 22:47:29.053 INFO  c.c.c.c.a.ApiAgentUserController - [operations] body {"ops":"inserv"}, q null [http-nio-8035-exec-23]

**Comment by hailiang-wang** [comment]
春松客服是如何部署的？是不是按照这个文档？
https://docs.chatopera.com/products/cskefu/deploy.html
---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)
