### ISSUE TITLE
访客端 Chrome 浏览器无法聊天，报错 kindeditor, Uncaught DOMException: Blocked a frame with origin 

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/cskefu#703]
## 现在行为

```
Uncaught DOMException: Blocked a frame with origin "https://my.cskefu.com" from accessing a cross-origin frame.
    at contents (https://oh-my.cskefu.com/js/jquery-1.10.2.min.js:5:23139)
    at Function.map (https://oh-my.cskefu.com/js/jquery-1.10.2.min.js:4:6171)
    at init.x.fn.<computed> [as contents] (https://oh-my.cskefu.com/js/jquery-1.10.2.min.js:5:23219)
    at KEditor.afterCreate (https://oh-my.cskefu.com/im/index.html?appid=0e8xuk&aiid=e3f4d3aa433a431bb350d5c9ffe0bac1&orgi=cskefu&client=9838810cfafc4614b6c130f5f1a2f3ae&type=text&userid=b5b8b527aae001d4ab8f18c373ec3324&sessionid=e71556bb-afa0-4494-9865-99b4ef3f3d52&t=1651150757813:75:52)
    at KEdit.afterCreate (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:5047:31)
    at ready (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:3701:25)
    at KEdit.init (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:3717:24)
    at new KEdit (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:3610:7)
    at _edit (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:3845:9)
    at KEditor.create (https://oh-my.cskefu.com/im/js/kindeditor/kindeditor.js:4978:26)
index.html?appid=0e8xuk&aiid=e3f4d3aa433a431bb350d5c9ffe0bac1&orgi=cskefu&client=9838810cfafc4614b6c130f5f1a2f3ae&type=text&userid=b5b8b527aae001d4ab8f18c373ec3324&sessionid=e71556bb-afa0-4494-9865-99b4ef3f3d52&t=1651150757813:528 Uncaught TypeError: Cannot read properties of undefined (reading 'sync')
    at sendMessage (index.html?appid=0e8xuk&aiid=e3f4d3aa433a431bb350d5c9ffe0bac1&orgi=cskefu&client=9838810cfafc4614b6c130f5f1a2f3ae&type=text&userid=b5b8b527aae001d4ab8f18c373ec3324&sessionid=e71556bb-afa0-4494-9865-99b4ef3f3d52&t=1651150757813:528:12)
    at HTMLButtonElement.onclick (index.html?appid=0e8xuk&aiid=e3f4d3aa433a431bb350d5c9ffe0bac1&orgi=cskefu&client=9838810cfafc4614b6c130f5f1a2f3ae&type=text&userid=b5b8b527aae001d4ab8f18c373ec3324&sessionid=e71556bb-afa0-4494-9865-99b4ef3f3d52&t=1651150757813:412:1064)
```

https://github.com/ff755/vue-kindeditor-demo/issues/11

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
问题分析及解决方案

https://blog.csdn.net/idomyway/article/details/86309348
