### ISSUE TITLE
java language level upgrade to 11

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/cskefu#714]
## 概述

Upgrade JDK fails.

Trace error.

```
contact-center_1  |     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:91)
contact-center_1  |     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:205)
contact-center_1  |     at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53)
contact-center_1  |     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154)
contact-center_1  |     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
contact-center_1  |     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
contact-center_1  |     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
contact-center_1  |     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
contact-center_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
contact-center_1  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
contact-center_1  |     at java.base/java.lang.Thread.run(Thread.java:829)
contact-center_1  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.micrometer.spring.web.servlet.WebMvcMetricsFilte
r]: Factory method 'webMetricsFilter' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with na
me 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.
class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.spri
ngframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]: Factory method 'requestMappingHandlerMapping' threw exception; nested exception is
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'openEntityManagerInViewInterceptor' defined in class path resource [or
g/springframework/boot/autoconfigure/orm/jpa/JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.class]: Initialization of bean failed; nested exce
ption is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/spri
ngframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundErr
or: javax/xml/bind/JAXBException
contact-center_1  |     at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
contact-center_1  |     at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
contact-center_1  |     ... 26 common frames omitted
contact-center_1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defi
```

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
现春松客服已经升级到 java jdk 11，language level 11.
