### ISSUE TITLE
开发环境运行报错

### ISSUE THREAD

**Issue by 12089897411** [chatopera/cskefu#715]
2022-07-01 14:04:10.721 INFO  com.chatopera.cc.Application - Starting Application on DESKTOP-DKDKR3M with PID 4472 (C:\Users\12089\Desktop\cskefu\contact-center\app\target\classes started by 12089 in C:\Users\12089\Desktop\cskefu\contact-center\app) [main] 
2022-07-01 14:04:10.722 INFO  com.chatopera.cc.Application - No active profile set, falling back to default profiles: default [main] 
2022-07-01 14:04:16.108 INFO  o.a.c.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8035"] [main] 
2022-07-01 14:04:16.132 INFO  o.a.c.core.StandardService - Starting service [Tomcat] [main] 
2022-07-01 14:04:16.133 INFO  o.a.c.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.43 [main] 
2022-07-01 14:04:16.298 INFO  o.a.c.c.C.[.[localhost].[/] - Initializing Spring embedded WebApplicationContext [localhost-startStop-1] 
2022-07-01 14:04:18.567 INFO  c.a.druid.pool.DruidDataSource - {dataSource-1} inited [localhost-startStop-1] 
2022-07-01 14:04:20.261 WARN  o.h.id.UUIDHexGenerator - HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead [localhost-startStop-1] 
2022-07-01 14:04:29.093 INFO  org.elasticsearch.plugins - [Delilah] modules [], plugins [], sites [] [localhost-startStop-1] 
2022-07-01 14:04:42.564 WARN  o.e.transport.netty - [Delilah] exception caught on transport layer [[id: 0xf81bb7c2, /127.0.0.1:56796 => /127.0.0.1:9300]], closing connection [elasticsearch[Delilah][transport_client_worker][T#1]{New I/O worker #1}] 
java.lang.NullPointerException: null
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleException(MessageChannelHandler.java:179)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:174)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:122)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by hailiang-wang** [comment]
ES 服务没有链接成功。

```
/127.0.0.1:56796 => /127.0.0.1:9300]], closing connection [elasticsearch[Delilah][transport_client_worker][Thttps://github.com/chatopera/cskefu/issues/1]{New I/O worker #1}]
java.lang.NullPointerException: null
```

参考文档：
https://docs.chatopera.com/products/cskefu/osc/engineering.html

**Comment by 12089897411** [comment]
spring.data.elasticsearch.properties.path.data=../data

spring.data.elasticsearch.cluster-name=elasticsearch
spring.data.elasticsearch.cluster-nodes=localhost:9300
spring.data.elasticsearch.local=false
spring.data.elasticsearch.repositories.enabled=true

**Comment by 12089897411** [comment]
使用localhost不可吗？
